In [2]:
##1) Import the numpy package under the name as np
import numpy as np

In [3]:
# 2)Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())


1.18.5
blas_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
blas_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
lapack_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
lapack_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/srv

In [4]:
# 3)Create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 4)How to find the memory size of any array
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [32]:
# 5) How to get the documentation of the numpy add function from the command line?
import numpy as np
python -c import numpy; import numpy.info(numpy.add)

SyntaxError: invalid syntax (<ipython-input-32-7abb59d15f1f>, line 3)

In [9]:
# 6) Create a null vector of size 10 but the fifth value which is 1
import numpy as np
x = np.zeros(10)
print(x)
print("Update fifth value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# 7) Create a vector with values ranging from 10 to 49?
import numpy as np
v = np.arange(10,49)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
All values except the first and last of the said vector:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [12]:
# 8) Reverse a vector (first element becomes last)?
import numpy as np
import numpy as np
x = np.arange(0, 10)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[0 1 2 3 4 5 6 7 8 9]
Reverse array:
[9 8 7 6 5 4 3 2 1 0]


In [15]:
# 9) Create a 3x3 matrix with values ranging from 0 to 8?
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# 10) Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [17]:
# 11) Create a 3x3 identity matrix
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 12) Create a 3x3x3 array with random values
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.34582883 0.30846447 0.68308505]
  [0.78048832 0.11426636 0.84536048]
  [0.29259797 0.60618212 0.30526745]]

 [[0.74541066 0.60297791 0.31705803]
  [0.92292952 0.73208015 0.94767063]
  [0.94820961 0.16982158 0.04572073]]

 [[0.46290903 0.39112127 0.02631631]
  [0.17346605 0.64848867 0.0746744 ]
  [0.65826094 0.12349617 0.52044709]]]


In [19]:
# 13) Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[5.10620737e-01 6.59541774e-01 1.71898420e-01 8.46558268e-01
  2.82222127e-01 3.72263262e-01 5.40010150e-01 4.64015704e-01
  1.81705004e-01 5.18720578e-01]
 [9.30489844e-01 7.98960568e-01 9.37502827e-03 5.20641089e-01
  1.86399023e-01 7.35940146e-01 4.41217446e-01 1.53957272e-01
  8.39193249e-01 8.38486011e-01]
 [6.39746592e-01 1.74980351e-01 3.78338430e-01 3.26665409e-04
  1.45503684e-02 1.19812247e-01 2.38392773e-01 3.02316905e-02
  2.95678528e-02 9.45798752e-01]
 [9.44260387e-01 2.39847661e-01 3.79908031e-01 7.60838694e-02
  9.99346488e-01 1.61742096e-01 7.40609458e-01 1.49176492e-01
  7.68516314e-01 5.87353712e-01]
 [4.62273076e-02 5.53739799e-01 8.65841507e-01 5.89126131e-01
  6.54574171e-01 1.09731075e-01 1.54268637e-01 8.50275347e-02
  2.49314191e-01 8.97941990e-01]
 [5.00413586e-01 3.42099940e-01 7.02203163e-01 5.34809395e-01
  8.09058339e-01 1.42847455e-01 3.21442923e-01 9.30376902e-01
  3.51841553e-01 3.68408609e-03]
 [2.75429300e-01 6.44151243e-01 1.62527069

In [21]:
# 14) Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()
print (m)

0.4546814121705553


In [23]:
# 15) Create a 2d array with 1 on the border and 0 inside
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
# 16) How to add a border (filled with 0's) around an existing array?
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
# 17) What is the result of the following expression?
#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#np.nan in set([np.nan])
#0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [27]:
# 18) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [29]:
# 19) Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
# 20) Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
